// Code generated by protoc-gen-gogo.
// source: destroy.proto
// DO NOT EDIT!

package warden

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type DestroyRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DestroyRequest) Reset()         { *m = DestroyRequest{} }
func (m *DestroyRequest) String() string { return proto.CompactTextString(m) }
func (*DestroyRequest) ProtoMessage()    {}

func (m *DestroyRequest) GetHandle() string {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return ""
}

type DestroyResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DestroyResponse) Reset()         { *m = DestroyResponse{} }
func (m *DestroyResponse) String() string { return proto.CompactTextString(m) }
func (*DestroyResponse) ProtoMessage()    {}

func init() {
}
