// Code generated by protoc-gen-gogo.
// source: limit_cpu.proto
// DO NOT EDIT!

package warden

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type LimitCpuRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	LimitInShares    *uint64 `protobuf:"varint,2,opt,name=limit_in_shares" json:"limit_in_shares,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LimitCpuRequest) Reset()         { *m = LimitCpuRequest{} }
func (m *LimitCpuRequest) String() string { return proto.CompactTextString(m) }
func (*LimitCpuRequest) ProtoMessage()    {}

func (m *LimitCpuRequest) GetHandle() string {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return ""
}

func (m *LimitCpuRequest) GetLimitInShares() uint64 {
	if m != nil && m.LimitInShares != nil {
		return *m.LimitInShares
	}
	return 0
}

type LimitCpuResponse struct {
	LimitInShares    *uint64 `protobuf:"varint,1,opt,name=limit_in_shares" json:"limit_in_shares,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LimitCpuResponse) Reset()         { *m = LimitCpuResponse{} }
func (m *LimitCpuResponse) String() string { return proto.CompactTextString(m) }
func (*LimitCpuResponse) ProtoMessage()    {}

func (m *LimitCpuResponse) GetLimitInShares() uint64 {
	if m != nil && m.LimitInShares != nil {
		return *m.LimitInShares
	}
	return 0
}

func init() {
}
