// Code generated by protoc-gen-gogo.
// source: link.proto
// DO NOT EDIT!

package warden

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type LinkRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	JobId            *uint32 `protobuf:"varint,2,req,name=job_id" json:"job_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LinkRequest) Reset()         { *m = LinkRequest{} }
func (m *LinkRequest) String() string { return proto.CompactTextString(m) }
func (*LinkRequest) ProtoMessage()    {}

func (m *LinkRequest) GetHandle() string {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return ""
}

func (m *LinkRequest) GetJobId() uint32 {
	if m != nil && m.JobId != nil {
		return *m.JobId
	}
	return 0
}

type LinkResponse struct {
	ExitStatus       *uint32       `protobuf:"varint,1,opt,name=exit_status" json:"exit_status,omitempty"`
	Stdout           *string       `protobuf:"bytes,2,opt,name=stdout" json:"stdout,omitempty"`
	Stderr           *string       `protobuf:"bytes,3,opt,name=stderr" json:"stderr,omitempty"`
	Info             *InfoResponse `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *LinkResponse) Reset()         { *m = LinkResponse{} }
func (m *LinkResponse) String() string { return proto.CompactTextString(m) }
func (*LinkResponse) ProtoMessage()    {}

func (m *LinkResponse) GetExitStatus() uint32 {
	if m != nil && m.ExitStatus != nil {
		return *m.ExitStatus
	}
	return 0
}

func (m *LinkResponse) GetStdout() string {
	if m != nil && m.Stdout != nil {
		return *m.Stdout
	}
	return ""
}

func (m *LinkResponse) GetStderr() string {
	if m != nil && m.Stderr != nil {
		return *m.Stderr
	}
	return ""
}

func (m *LinkResponse) GetInfo() *InfoResponse {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
}
