// Code generated by protoc-gen-gogo.
// source: copy_out.proto
// DO NOT EDIT!

package warden

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type CopyOutRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	SrcPath          *string `protobuf:"bytes,2,req,name=src_path" json:"src_path,omitempty"`
	DstPath          *string `protobuf:"bytes,3,req,name=dst_path" json:"dst_path,omitempty"`
	Owner            *string `protobuf:"bytes,4,opt,name=owner" json:"owner,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CopyOutRequest) Reset()         { *m = CopyOutRequest{} }
func (m *CopyOutRequest) String() string { return proto.CompactTextString(m) }
func (*CopyOutRequest) ProtoMessage()    {}

func (m *CopyOutRequest) GetHandle() string {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return ""
}

func (m *CopyOutRequest) GetSrcPath() string {
	if m != nil && m.SrcPath != nil {
		return *m.SrcPath
	}
	return ""
}

func (m *CopyOutRequest) GetDstPath() string {
	if m != nil && m.DstPath != nil {
		return *m.DstPath
	}
	return ""
}

func (m *CopyOutRequest) GetOwner() string {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return ""
}

type CopyOutResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CopyOutResponse) Reset()         { *m = CopyOutResponse{} }
func (m *CopyOutResponse) String() string { return proto.CompactTextString(m) }
func (*CopyOutResponse) ProtoMessage()    {}

func init() {
}
