// Code generated by protoc-gen-gogo.
// source: error.proto
// DO NOT EDIT!

package warden

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ErrorResponse struct {
	Message          *string  `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Data             *string  `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	Backtrace        []string `protobuf:"bytes,3,rep,name=backtrace" json:"backtrace,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}

func (m *ErrorResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *ErrorResponse) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func (m *ErrorResponse) GetBacktrace() []string {
	if m != nil {
		return m.Backtrace
	}
	return nil
}

func init() {
}
