// Code generated by protoc-gen-gogo.
// source: limit_memory.proto
// DO NOT EDIT!

package warden

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type LimitMemoryRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	LimitInBytes     *uint64 `protobuf:"varint,2,opt,name=limit_in_bytes" json:"limit_in_bytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LimitMemoryRequest) Reset()         { *m = LimitMemoryRequest{} }
func (m *LimitMemoryRequest) String() string { return proto.CompactTextString(m) }
func (*LimitMemoryRequest) ProtoMessage()    {}

func (m *LimitMemoryRequest) GetHandle() string {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return ""
}

func (m *LimitMemoryRequest) GetLimitInBytes() uint64 {
	if m != nil && m.LimitInBytes != nil {
		return *m.LimitInBytes
	}
	return 0
}

type LimitMemoryResponse struct {
	LimitInBytes     *uint64 `protobuf:"varint,1,opt,name=limit_in_bytes" json:"limit_in_bytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LimitMemoryResponse) Reset()         { *m = LimitMemoryResponse{} }
func (m *LimitMemoryResponse) String() string { return proto.CompactTextString(m) }
func (*LimitMemoryResponse) ProtoMessage()    {}

func (m *LimitMemoryResponse) GetLimitInBytes() uint64 {
	if m != nil && m.LimitInBytes != nil {
		return *m.LimitInBytes
	}
	return 0
}

func init() {
}
