// Code generated by protoc-gen-gogo.
// source: create.proto
// DO NOT EDIT!

package warden

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type CreateRequest_BindMount_Mode int32

const (
	CreateRequest_BindMount_RO CreateRequest_BindMount_Mode = 0
	CreateRequest_BindMount_RW CreateRequest_BindMount_Mode = 1
)

var CreateRequest_BindMount_Mode_name = map[int32]string{
	0: "RO",
	1: "RW",
}
var CreateRequest_BindMount_Mode_value = map[string]int32{
	"RO": 0,
	"RW": 1,
}

func (x CreateRequest_BindMount_Mode) Enum() *CreateRequest_BindMount_Mode {
	p := new(CreateRequest_BindMount_Mode)
	*p = x
	return p
}
func (x CreateRequest_BindMount_Mode) String() string {
	return proto.EnumName(CreateRequest_BindMount_Mode_name, int32(x))
}
func (x *CreateRequest_BindMount_Mode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CreateRequest_BindMount_Mode_value, data, "CreateRequest_BindMount_Mode")
	if err != nil {
		return err
	}
	*x = CreateRequest_BindMount_Mode(value)
	return nil
}

type CreateRequest struct {
	BindMounts       []*CreateRequest_BindMount `protobuf:"bytes,1,rep,name=bind_mounts" json:"bind_mounts,omitempty"`
	GraceTime        *uint32                    `protobuf:"varint,2,opt,name=grace_time" json:"grace_time,omitempty"`
	Handle           *string                    `protobuf:"bytes,3,opt,name=handle" json:"handle,omitempty"`
	Network          *string                    `protobuf:"bytes,4,opt,name=network" json:"network,omitempty"`
	Rootfs           *string                    `protobuf:"bytes,5,opt,name=rootfs" json:"rootfs,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}

func (m *CreateRequest) GetBindMounts() []*CreateRequest_BindMount {
	if m != nil {
		return m.BindMounts
	}
	return nil
}

func (m *CreateRequest) GetGraceTime() uint32 {
	if m != nil && m.GraceTime != nil {
		return *m.GraceTime
	}
	return 0
}

func (m *CreateRequest) GetHandle() string {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return ""
}

func (m *CreateRequest) GetNetwork() string {
	if m != nil && m.Network != nil {
		return *m.Network
	}
	return ""
}

func (m *CreateRequest) GetRootfs() string {
	if m != nil && m.Rootfs != nil {
		return *m.Rootfs
	}
	return ""
}

type CreateRequest_BindMount struct {
	SrcPath          *string                       `protobuf:"bytes,1,req,name=src_path" json:"src_path,omitempty"`
	DstPath          *string                       `protobuf:"bytes,2,req,name=dst_path" json:"dst_path,omitempty"`
	Mode             *CreateRequest_BindMount_Mode `protobuf:"varint,3,req,name=mode,enum=warden.CreateRequest_BindMount_Mode" json:"mode,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *CreateRequest_BindMount) Reset()         { *m = CreateRequest_BindMount{} }
func (m *CreateRequest_BindMount) String() string { return proto.CompactTextString(m) }
func (*CreateRequest_BindMount) ProtoMessage()    {}

func (m *CreateRequest_BindMount) GetSrcPath() string {
	if m != nil && m.SrcPath != nil {
		return *m.SrcPath
	}
	return ""
}

func (m *CreateRequest_BindMount) GetDstPath() string {
	if m != nil && m.DstPath != nil {
		return *m.DstPath
	}
	return ""
}

func (m *CreateRequest_BindMount) GetMode() CreateRequest_BindMount_Mode {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return CreateRequest_BindMount_RO
}

type CreateResponse struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}

func (m *CreateResponse) GetHandle() string {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return ""
}

func init() {
	proto.RegisterEnum("warden.CreateRequest_BindMount_Mode", CreateRequest_BindMount_Mode_name, CreateRequest_BindMount_Mode_value)
}
