// Code generated by protoc-gen-gogo.
// source: spawn.proto
// DO NOT EDIT!

package warden

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SpawnRequest struct {
	Handle           *string         `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	Script           *string         `protobuf:"bytes,2,req,name=script" json:"script,omitempty"`
	Privileged       *bool           `protobuf:"varint,3,opt,name=privileged,def=0" json:"privileged,omitempty"`
	Rlimits          *ResourceLimits `protobuf:"bytes,4,opt,name=rlimits" json:"rlimits,omitempty"`
	DiscardOutput    *bool           `protobuf:"varint,5,opt,name=discard_output,def=0" json:"discard_output,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *SpawnRequest) Reset()         { *m = SpawnRequest{} }
func (m *SpawnRequest) String() string { return proto.CompactTextString(m) }
func (*SpawnRequest) ProtoMessage()    {}

const Default_SpawnRequest_Privileged bool = false
const Default_SpawnRequest_DiscardOutput bool = false

func (m *SpawnRequest) GetHandle() string {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return ""
}

func (m *SpawnRequest) GetScript() string {
	if m != nil && m.Script != nil {
		return *m.Script
	}
	return ""
}

func (m *SpawnRequest) GetPrivileged() bool {
	if m != nil && m.Privileged != nil {
		return *m.Privileged
	}
	return Default_SpawnRequest_Privileged
}

func (m *SpawnRequest) GetRlimits() *ResourceLimits {
	if m != nil {
		return m.Rlimits
	}
	return nil
}

func (m *SpawnRequest) GetDiscardOutput() bool {
	if m != nil && m.DiscardOutput != nil {
		return *m.DiscardOutput
	}
	return Default_SpawnRequest_DiscardOutput
}

type SpawnResponse struct {
	JobId            *uint32 `protobuf:"varint,1,req,name=job_id" json:"job_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SpawnResponse) Reset()         { *m = SpawnResponse{} }
func (m *SpawnResponse) String() string { return proto.CompactTextString(m) }
func (*SpawnResponse) ProtoMessage()    {}

func (m *SpawnResponse) GetJobId() uint32 {
	if m != nil && m.JobId != nil {
		return *m.JobId
	}
	return 0
}

func init() {
}
